### ISSUE TITLE
Error when searching for any concept keyword that generates a long querystring (api/concept/parents?idents=etc)

### ISSUE THREAD

**Issue by sgchoe** [uwrit/leaf#220]
Our Leaf instance is v3.2.  The LeafDB.app.concept table is loaded with SNOMED and CPT concepts.  Searching for 'knee' returns 'knee of' as one of the hint results and clicking on 'knee of' results in an error.  This should also affect other keywords that return many results and, therefore, a querystring that exceeds the web server's limit such that an error is returned (IIS in our case).  The UI does nothing after 'knee of' is selected but using browser inspection tools shows a 404 occurring, as shown in the following screenshots.  The querystring generated in the screenshot is 3491 characters.  The 404 matches a 404.15 recorded in the IIS logs for the same request and is consistent with the expected response documented here: https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/.  Please let me know if I can provide any additional information or details.

![leaf_concept_search_knee_1](https://user-images.githubusercontent.com/51516907/60208034-f0532d80-981c-11e9-93ab-1b43b0d58237.png)

![leaf_concept_search_knee_2](https://user-images.githubusercontent.com/51516907/60208053-0103a380-981d-11e9-8ac4-29f481f5eeed.png)

**Comment by ndobb** [comment]
@sgchoe thanks, this is really helpful. So essentially the number of concepts which include those terms is sufficiently large such that the API GET request length exceeds what the server config allows.

Any idea what your current IIS instance is set to regarding max URL length?

I can think of a few options here:

1) **We arbitrarily select the first n concepts (e.g., 20) and request only those**. I think this may be the best option as any more than that would likely be more than the user would be willing/able to sift through, and in any case I think that is a simple, reasonable solution.

2) **We turn the current GET API request into a POST**. This would place the request parameters in the body rather than the URL, within which the length limit is far larger. I'm not particularly fond of this option as **a)** in REST terms this should be a GET, as the call is not modifying any app state (as a POST would be expected to do), and **b)** the advantages for the user are minimal (i.e., do they really benefit by being able/forced to sift through 1000+ more concepts?)

3) **We add an appsettings property, such as `maxSelectableConceptHints`, which the admin could explicitly set**. This value would be passed to and used by the client app. This would allow sites to tailer the allowed count to their local request URL length limits. I don't think this option is quite ideal, as it seems an unnecessary burden to my mind for an admin to need to be concerned about this. I'm open to others thoughts though.

I'm leaning toward option 1 as the simplest and most reasonable option. A `conceptId` GUID represented as a string is 36 characters, and adding the additional '&ident=' adds 7, so that's 43 per concept. Assuming the beginning of the URL (e.g. https://leaf.university.edu/api/concept/search/parents?) has about 60 characters, so 60 + (43 * 20) = 920 characters, which should be far below the limit of a given web server. We could even do more than a max 20 concepts.

@sgchoe @cspital thoughts?

**Comment by sgchoe** [comment]
@ndobb our IIS instance has query string length to 2048, which I believe is the IIS default value.  Of the three options, I think my preference would be for option 1 as well.  The concept hint UI already displays the count as being '20+ concept(s)' so a cap on the number of results returned by what's likely to be a fairly broad search seems reasonable.  This could also be revisited in the future if you receive usage feedback indicating that a different solution might be better.  Thanks.

**Comment by ndobb** [comment]
Great, thanks @sgchoe. I'll implement that in the patch.

**Comment by ndobb** [comment]
@sgchoe, when you have a moment would you mind pulling down the search-fix branch (https://github.com/uwrit/leaf/tree/search-fix) and testing the client? This branch should fix 3 issues: #221 the admin tab tooltip issue, #220 the search issue, and extra bonus #190. Thanks.

**Comment by sgchoe** [comment]
@ndobb, all of the fixes look great, especially the snackbar-style implementation of the admin save confirmation.  Thanks.

**Comment by ndobb** [comment]
Great. This has been merged into master and released as version [3.2.1](https://github.com/uwrit/leaf/releases/tag/v3.2.1.).
