### ISSUE TITLE
Database server requirements

### ISSUE THREAD

**Issue by chrisortman** [uwrit/leaf#324]
Why does the Leaf application database need to be on the same server as the clinical database?

**Comment by ndobb** [comment]
Hi @chrisortman, thanks for your question. The Leaf application database must be on the same server as the clinical database because occasionally Leaf will run queries which join cached patient IDs from the app database to the clinical database. Specifically, the flow is:

1. User runs cohort definition query on the 'Find Patients' screen.
2. The Leaf API executes the query and caches the patient IDs in the app database `app.Cohort` table.
3. User clicks 'Visualize' or 'Patient List'.
4. In order to generate statistics and/or row-level data for the cohort, Leaf runs a query joining the cached patients in the `app.Cohort` table to the demographics data in the clinical database.

So the query in step 4 isn't feasible if the databases are on separate servers.

Let me know if that clears things up!

**Comment by chrisortman** [comment]
Makes sense, thanks for the info
