### ISSUE TITLE
Visualization tab = patient age at encounter

### ISSUE THREAD

**Issue by elg8993** [uwrit/leaf#352]
Would it be possible to change the patient age visualization to be the patient age at the encounter rather than the patient's current age (as of query date)? Or include both if there are LEAF users who prefer the current age information?

**Comment by ndobb** [comment]
Hi @elg8993 , thanks for your question. My understanding is that you're referring to this screen:
![image](https://user-images.githubusercontent.com/10424962/90159232-f4a21900-dd44-11ea-825c-4deec96a8cc4.png)

The reason Leaf uses current age is less about user preference (though we also assume that to be intuitive to a certain extent), and more because calculating patient age from inferring dates from a user's arbitrary inclusion criteria is trickier than it seems at first blush. For example, if a query has 2+ panels with date filters, which would Leaf use?
![image](https://user-images.githubusercontent.com/10424962/90159562-6e3a0700-dd45-11ea-9e29-0fe8cb4c40f0.png)

Or what if the criteria were sequential? In this example, would users be able to know which dates Leaf was calculating age from?
![image](https://user-images.githubusercontent.com/10424962/90159760-b3f6cf80-dd45-11ea-8b31-607f00af2418.png)

Our subjective take on this problem is that it would likely be confusing or unclear, no matter how we tried to do it. 

As an alternative, you can always export data to REDCap (then perhaps to Excel or a stats program) and calculate the ages as you'd like, though of course this is more work.

Hope this helps.

**Comment by elg8993** [comment]
Ok, thanks.

-Emma

--
Emma Gause, MA
Research Assistant, Harborview Injury Prevention & Research Center
MS Student, Department of Epidemiology
University of Washington
egause@uw.edu<mailto:egause@uw.edu>
<mailto:egause@uw.edu>

[signature_1332166288]
