### ISSUE TITLE
Number of encounters rather than number of patients

### ISSUE THREAD

**Issue by elg8993** [uwrit/leaf#355]
Is it possible to change the query results to provide the number of **encounters** rather than the number of patients? For some issues it is common to see repeat patients in different encounters. The number of encounters also is a better measure of utilization/hospital burden. 

(Currently my work around is to use the "at least#x" option and then manually add up the different age/gender/race categories multiplying by the # to get the values by encounter rather than patient, but this is time-consuming and error-prone).

**Comment by ndobb** [comment]
This is a request we get from time to time, but at the moment we have no plans to implement this. Our reasoning is less to do with technical issues, and more to do with odd or surprising quirks about what constitutes an "encounter" in EHRs, that would likely be unintuitive for users.

For example, within EHRs at our institution, new "encounters" are sometimes created simply by admitted patients being transferred, having certain procedures performed, etc. This is despite the fact that the patient is still admitted within what rational clinical folks would still consider the same single "encounter".

Add to that other "encounter" types such telephone calls, med orders, bills (yes, under certain circumstances just generating bills within EHRs creates a new "encounter"), you have quite a confusing mess of what really are not, but are stored in EHRs as, encounters.

So rather than attempt to address that rat's nest of messy data (which could very possibly skew or distort user research), we intend to stick to just unique patient counts for the time being.

As an alternative, you can always export row-level encounter data and conduct analysis as you see fit.

**Comment by elg8993** [comment]
Ok, thanks for explaining. I will continue to export the row-level data.

Best,
Emma

--
Emma Gause, MA
Research Assistant, Harborview Injury Prevention & Research Center
MS Student, Department of Epidemiology
University of Washington
egause@uw.edu<mailto:egause@uw.edu>
<mailto:egause@uw.edu>

[signature_1615191848]
