### ISSUE TITLE
REDCap import fails

### ISSUE THREAD

**Issue by pj00** [uwrit/leaf#360]
I am still on Leaf 3.6

I enter my token, then the MRN field, and click Import Project.  The import modal briefly shows the progress indicator, then errors out.  The modal does seem to be doing some amount of processing before it errors out, b/c I can see the content changing and the progress indicator moving.  But, it happens so fast I can't actually read what it's doing before the error.

![image](https://user-images.githubusercontent.com/18190568/91859207-c458e680-ec2f-11ea-885e-6ef9e5f0c11c.png)

The log shows it is failing here:
https://github.com/uwrit/leaf/blob/b896aa790d700194fdb5f1cd6704fce703bb20c5/src/server/Services/Import/ImportIdentifierMappingService.cs#L137

```json
{
	"Timestamp": "2020-09-01T08:11:06.1707520-05:00",
	"Level": "Error",
	"MessageTemplate": "Failed to upsert import records. ImportMetadataId:{id} Error:{Error}",
	"Properties": {
		"id": "f4d25c97-54ec-ea11-ac47-90b11c4c828b",
		"Error": "System.NullReferenceException: Object reference not set to an instance of an object.\n   
		at Services.Import.ImportIdentifierMappingService.GetMappingQuery(MappingQuery mapping, IEnumerable`1 ids) in /opt/leaf/leaf/src/server/Services/Import/ImportIdentifierMappingService.cs:line 137\n   at Services.Import.ImportIdentifierMappingService.GetMappingRecords(IEnumerable`1 ids) in /opt/leaf/leaf/src/server/Services/Import/ImportIdentifierMappingService.cs:line 91\n   at Services.Import.ImportIdentifierMappingService.MapIds(IEnumerable`1 records) in /opt/leaf/leaf/src/server/Services/Import/ImportIdentifierMappingService.cs:line 46\n   at Model.Import.DataImporter.ImportData(Guid id, IEnumerable`1 records) in /opt/leaf/leaf/src/server/Model/Import/DataImporter.cs:line 112\n   at API.Controllers.ImportController.ImportData(Guid id, ImportDataRecordDTO data, DataImporter importer) in /opt/leaf/leaf/src/server/API/Controllers/ImportController.cs:line 183",
		"SourceContext": "API.Controllers.ImportController",
		"ActionId": "98566432-5c85-4eee-a1d3-df5e497494c0",
		"ActionName": "API.Controllers.ImportController.ImportData (API)",
		"RequestId": "0HM2APO5OOVRQ:00000001",
		"RequestPath": "/api/import/data/f4d25c97-54ec-ea11-ac47-90b11c4c828b",
		"CorrelationId": null,
		"ConnectionId": "0HM2APO5OOVRQ",
		"SessionId": "8f11883e-27f0-4682-8ade-487ddbaa4d41",
		"User": "xxx@xxx@urn:leaf:iss:dev.leaf.tld"
	}
}
```

**Comment by ndobb** [comment]
The REDCap Import feature was unfortunately added in faster than we could document, and as we'd (incorrectly) assumed other institutions weren't using it, we've been lazy about documenting how to configure it. We've also not yet added a component in the Leaf Admin UI to configure it. Sorry about that.

So: you need to first configure a SQL statement that maps MRNs to whatever [`PersonId field`](https://github.com/uwrit/leaf/blob/master/src/server/API/appsettings.json#L55) you've configured. For example:

```sql
INSERT INTO [app].[ImportPatientMappingQuery] (Lock, SqlStatement, SqlFieldSourceId, LastChanged, ChangedBy)
SELECT
    Lock             = 'X'
  , SqlStatement     = 'SELECT
                            X.PersonId     /* <- PersonId Leaf needs */
                          , X.MrnField     /* <- MRNs to map REDCap MRNs to */
		        FROM dbo.some_mrn_table AS X'
  , SqlFieldSourceId = 'MrnField'          /* <- Name of the 2nd field above */
  , LastChanged      = GETDATE()
  , ChangedBy        = 'ndobb'
```

**Comment by pj00** [comment]
We're using Leaf with a de-identified i2b2 instance and, unfortunately, I'm very much a noob when it comes to both i2b2 and REDCap.  Hopefully, you can hold my hand a little bit here.

The REDCap project I'm trying to import is one that was created via a Leaf export.  When I try to import, I choose `PersonId` as the MRN field:

![image](https://user-images.githubusercontent.com/18190568/91892901-04808f00-ec59-11ea-8a9c-6be384460cad.png)

So, it seems like I should be mapping PersonId to PersonId, but I'm not clear on what the `dbo.some_mrn_table` is.

I should also point out that I'm trying to do this import for proof-of-concept purposes, just so I can demonstrate "you can import from REDCap".  The data I'm trying to import is probably not the most practical of examples.

**Comment by ndobb** [comment]
Right, so I should have provided more context about the assumptions made with REDCap imports. One assumption is that the Leaf instance being used has identified data (and thus MRNs). Further, patients at many institutions can have multiple MRNs (as MRNs can change over time, or between hospitals within the same institution, etc.). Because of that, most institutions have some sort of sole unique identifier for a given patient (ie, a Master Patient Index), besides MRNs.

So when these places use Leaf, the most typical use case is to have their local Master Patient Index be the Leaf `PersonId`.

However, providers at most institutions still identify patients by MRN, and it's typically MRNs which end up in REDCap projects. So whenever the Leaf REDCap Import is used, Leaf assumes it needs to map incoming `MRNs` -> `PersonIds`.

The way we handle that is via an arbitrary SQL statement in the `app.ImportPatientMappingQuery` table, which returns one column with the `PersonId`, and another column with the `MRN`. Leaf runs this SQL and maps the REDCap MRNs accordingly.

In your case though, you don't have MRNs (as it's an already de-identified i2b2 database), and the REDCap project you're importing from has `PersonIds`.

**I'd suggest then tricking Leaf by giving it a SQL statement where the `PersonId` and `MRN` are the same thing**. Something like:

```sql
SELECT 
      PATIENT_NUM
    , DummyMRN = PATIENT_NUM
FROM dbo.PATIENT_DIMENSION
```

I've never tried this but I can't think of a reason it wouldn't work. Can you try that and let me know?

**Comment by ndobb** [comment]
As an aside @pj00, just out of curiosity would you mind me asking what institution you're from? Happy to chat by email if that's easier (ndobb@uw.edu). BTW we have a monthly Leaf developers meeting that you're welcome to attend if you're ever interested.

**Comment by pj00** [comment]
That gets me a little closer, I think, but now I get this:

```json
{
	"Timestamp": "2020-09-03T08:18:10.9476857-05:00",
	"Level": "Error",
	"MessageTemplate": "Failed to upsert import records. ImportMetadataId:{id} Error:{Error}",
	"Properties": {
		"id": "f3417ce8-e7ed-ea11-ac47-90b11c4c828b",
		"Error": "System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting the varchar value '0_-1373258231' to data type int.\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\n   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)\n   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)\n   at System.Data.SqlClient.SqlDataReader.Read()\n   at Services.Import.ImportIdentifierMappingService.GetMappingRecords(IEnumerable`1 ids) in /opt/leaf/leaf/src/server/Services/Import/ImportIdentifierMappingService.cs:line 100\n   at Services.Import.ImportIdentifierMappingService.MapIds(IEnumerable`1 records) in /opt/leaf/leaf/src/server/Services/Import/ImportIdentifierMappingService.cs:line 46\n   at Model.Import.DataImporter.ImportData(Guid id, IEnumerable`1 records) in /opt/leaf/leaf/src/server/Model/Import/DataImporter.cs:line 112\n   at API.Controllers.ImportController.ImportData(Guid id, ImportDataRecordDTO data, DataImporter importer) in /opt/leaf/leaf/src/server/API/Controllers/ImportController.cs:line 183\nClientConnectionId:002882b5-db62-4bfc-bcfb-735ca0e48cfe\nError Number:245,State:1,Class:16",
		"SourceContext": "API.Controllers.ImportController",
		"ActionId": "98566432-5c85-4eee-a1d3-df5e497494c0",
		"ActionName": "API.Controllers.ImportController.ImportData (API)",
		"RequestId": "0HM2APO5OP048:00000002",
		"RequestPath": "/api/import/data/f3417ce8-e7ed-ea11-ac47-90b11c4c828b",
		"CorrelationId": null,
		"ConnectionId": "0HM2APO5OP048",
		"SessionId": "23aa930d-6e78-4f09-bb50-8e9c6054ffbb",
		"User": "pflanagan@uiowa.edu@urn:leaf:iss:dev.leaf.tld"
	}
}
```

I don't know why, but my REDCap `PersonId`s look like this:

![image](https://user-images.githubusercontent.com/18190568/92121842-5d1e6c00-edc0-11ea-97f9-763c35c8db54.png)

So, I think either Leaf or REDCap transformed the `PersonId` when I did the Leaf export?

**Comment by ndobb** [comment]
Got it. This makes sense. So there are a few issues, it appears:

1. Your export looks like it was in de-identified mode (the negative values in the `PersonId` suggest they were randomly generated by Leaf, and don't exist in the i2b2 database), so they'll never match to their original i2b2 identifiers.
2. Right, in the Patient List, Leaf prepends an integer before the `PersonId`to make sure it's unique (because in a federated Leaf setup with multiple institutions, it's possible patients in different Leaf instances have the same identifier). So in this case Leaf added a '0' before each `PersonId`.
3. In the mapping SQL statement, the `DummyMRN` field is an integer, but the imported `PersonIds` are strings. Leaf is wrapping your SqlStatement and trying to join the two, which causes the error above. You can probably fix this by changing your SQL statement to 

```sql
SELECT 
      PATIENT_NUM
    , DummyMRN = CONVERT(NVARCHAR(20),PATIENT_NUM)
FROM dbo.PATIENT_DIMENSION
```

However fixing (3) would still wouldn't fix  the problem of the de-identified patient IDs never matching what's in i2b2.

So in order to get this to work, you'd need to:
1. Do a new export in Identified mode (to preserve true i2b2 `PersonIds`.
2. In REDCap, strip away the `0_` Leaf added to the `PersonId.
3. Update your SQL statement as suggested above.

That *should* do it. As I mentioned, if you have MRNs (in a non-test scenario) you wouldn't have to jump through hoops like this. Also, as an alternative to (2), you could create a new Dataset which includes the i2b2 PAT_NUM, add that to the Patient LIst, and export that, which would preserve the pure i2b2 identifiers, though at this point it's probably easier just to do the steps above. 

Let me know if any of this doesn't make sense.

**Comment by ndobb** [comment]
👍 of course, that's totally understandable. Let me know if you have other questions.
