### ISSUE TITLE
API still requests authentication despite compiling API in debug mode.

### ISSUE THREAD

**Issue by yobroyem0** [uwrit/leaf#370]

**Comment by ndobb** [comment]
@yobroyem0 please take the time to describe the issue you are seeing. Issues with no description or context will  be closed without resolution in the future.

Compiling the API in debug mode simply allows Leaf to used UNSECURED auth without throwing errors. If you configure SAML auth or use Apache, etc., you'll still need to authenticate because that is unrelated to how you've compiled the API.
