### ISSUE TITLE
Request: configurable display names for basic demographics

### ISSUE THREAD

**Issue by am202** [uwrit/leaf#541]
In some cases it might be helpful if we could pick new display names for the column headers on the Patient List.  In our specific case, we don't want to display patient MRNs, but we do want to display a different patient identifier that we call a subject id or study id here.  We're currently pulling the subject id as if it were the MRN in our Basic Demographics dataset query, and it's fine calling it an MRN at that level.  We just don't want users to worry that we might be showing MRNs in the patient list when they see the "Mrn" column header, so simply changing the display name that appears there would be sufficient for us.

(Also, I don't think we can use the personId field for our subject id.  We're currently using the OMOP model, and we're putting the numeric OMOP person_id there, and that's the only patient identifier shared across all of our tables.  Our subject id is a string column that only exists in one table.)

I would envision this feature being available when editing the Basic Demographics dataset in the Admin section.  Maybe the Expected Columns list to the left of the SQL Query could continue to show the FHIR-based names for the required columns but also have a separate editable display name.  But even if it could be implemented in a different way, having any possible way to change those display names would be appreciated.

**Comment by ndobb** [comment]
@am202 I think this is a great idea. This also relates to requests we've gotten to make certain demographics fields optional rather than all required, as they are currently. We can prioritize this for the next release.

Editing the field titles in the Admin section also makes sense to me. I think we can probably store the optional names as JSON in the [app.DemographicQuery table](https://github.com/uwrit/leaf/blob/master/src/db/obj/app.DemographicQuery.Table.sql#L13).

**Comment by am202** [comment]
Sounds good to me, thanks!
